name: 'Kyria'
on: push
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["kyria_dongle"]'
      branches: '["Benaan/zmk/main"]'
